MOUSEKEY_ENABLE   = yes
RGBLIGHT_TWINKLE  = no
RGBLIGHT_STARTUP_ANIMATION = no
RGBLIGHT_ANIMATIONS = no
CONSOLE_ENABLE    = no         # Console for debug(+400)
COMMAND_ENABLE    = no
NKRO_ENABLE = yes
